apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../_base

namespace: prod
namePrefix: prod-

commonLabels:
  environment: prod

replicas:
- count: 3
  name: appxhub

configMapGenerator:
- envs:
  - .env.prod.config
  name: appxhub-config
    

secretGenerator:
- envs:
  - .env.prod
  name: appxhub-secret
  type: Opaque

patches:
- path: appxhub_prod-deploy.patch.yml
labels:
- includeSelectors: true
  pairs:
    environment: prod
