---
# System settings
timezone: UTC
system_locale: en_US.UTF-8

# Kubernetes settings
kubernetes_version: "1.28.0"
container_runtime: docker
pod_cidr: "10.244.0.0/16"
service_cidr: "10.96.0.0/12"

# Security settings
ssh_port: 22
fail2ban_bantime: 3600
fail2ban_findtime: 600
fail2ban_maxretry: 3

# Package settings
package_update: true
package_upgrade: true

# System limits
system_limits:
  nofile:
    soft: 65535
    hard: 65535
  nproc:
    soft: 65535
    hard: 65535

# Firewall settings
firewall_rules:
  - { port: 22, proto: tcp, comment: "SSH" }
  - { port: 6443, proto: tcp, comment: "Kubernetes API Server" }
  - { port: 2379, proto: tcp, comment: "etcd server client API" }
  - { port: 2380, proto: tcp, comment: "etcd peer communication" }
  - { port: 10250, proto: tcp, comment: "Kubelet API" }
  - { port: 10259, proto: tcp, comment: "kube-scheduler" }
  - { port: 10257, proto: tcp, comment: "kube-controller-manager" }
  - { port: "30000:32767", proto: tcp, comment: "NodePort Services" } 