apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: appxhub-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: appxhub
  minReplicas: 1
  maxReplicas: 3
  