apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../_base

namespace: dev
namePrefix: dev-

commonLabels:
  environment: dev

replicas:
  - name: appxhub
    count: 2

configMapGenerator:
  - name: appxhub-config
    envs:
      - .env.dev.config
    

secretGenerator:
  - name: appxhub-secret
    envs:
      - .env.dev
    type: Opaque

patches:
  - path: appxhub_dev-deploy.patch.yml
  - path: appxhub_dev-hpa.patch.yml
  - path: appxhub_dev-svc.patch.yml