---
- name: Apply Security Hardening
  hosts: kubernetes
  become: true
  gather_facts: true

  roles:
    - security

  tasks:
    - name: Ensure SSH hardening is applied
      include_role:
        name: security
        tasks_from: ssh_hardening.yml

    - name: Ensure system hardening is applied
      include_role:
        name: security
        tasks_from: system_hardening.yml

    - name: Ensure firewall rules are applied
      include_role:
        name: security
        tasks_from: firewall.yml

  post_tasks:
    - name: Reboot system if required
      reboot:
        msg: "Reboot initiated by Ansible for security updates"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: reboot_required is defined and reboot_required 