---
- name: Configure Kubernetes Cluster Nodes
  hosts: kubernetes
  become: true
  gather_facts: true

  roles:
    - common
    - security
    - packages
    - kubernetes

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update yum cache
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"

  post_tasks:
    - name: Reboot system if required
      reboot:
        msg: "Reboot initiated by Ansible for updates"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: reboot_required is defined and reboot_required 