---
- name: Install UFW if not present
  package:
    name: ufw
    state: present

- name: Reset UFW to defaults
  ufw:
    state: reset
    policy: deny

- name: Allow SSH
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow Kubernetes API Server
  ufw:
    rule: allow
    port: '6443'
    proto: tcp

- name: Allow etcd server client API
  ufw:
    rule: allow
    port: '2379'
    proto: tcp

- name: Allow etcd peer communication
  ufw:
    rule: allow
    port: '2380'
    proto: tcp

- name: Allow Kubelet API
  ufw:
    rule: allow
    port: '10250'
    proto: tcp

- name: Allow kube-scheduler
  ufw:
    rule: allow
    port: '10259'
    proto: tcp

- name: Allow kube-controller-manager
  ufw:
    rule: allow
    port: '10257'
    proto: tcp

- name: Allow NodePort Services
  ufw:
    rule: allow
    port: '30000:32767'
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny 