---
- name: Configure SSH hardening
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      # SSH Hardening
      PermitRootLogin no
      PasswordAuthentication no
      ChallengeResponseAuthentication no
      UsePAM yes
      X11Forwarding no
      AllowTcpForwarding no
      ClientAliveInterval 300
      ClientAliveCountMax 2
      MaxAuthTries 3
      MaxSessions 3
      LoginGraceTime 60
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK - SSH HARDENING"

- name: Restart SSH service
  service:
    name: sshd
    state: restarted
    enabled: yes 